name: Doorlock
version: 1.0
main: dev.jones.doorlock.Doorlock
api-version: 1.14
authors: [ _joones ]
description: Lock doors with keys.
commands:
  dldebug:
    description: Debug Command(Only intended for developers, can be enabled in the Doorlock class)
    permission: doorlock.debug
    permission-message: §cYou are not permitted to use this command!
  doorlock:
    description: Can be used to reload the plugin, to check for updates or check the plugin version
    permission: doorlock.manage
    permission-message: §cYou are not permitted to use this command!
    usage: §cUse /doorlock <version|update|reload>
  unlock:
    description: Unlocks the block you are looking at.
    permission: doorlock.unlock
    permission-message: §cYou are not permitted to use this command!
    usage: §cUse /unlock without arguments

