name: Doorlock
version: 1.1.0
main: dev.jones.doorlock.Doorlock
api-version: 1.17
authors: [ _joones ]
description: Lock doors with keys.
commands:
  dldebug:
    description: Debug Command(Only intended for developers, can be enabled in the Doorlock class)
    permission: doorlock.debug
    permission-message: §cYou are not permitted to use this command!
  doorlock:
    description: Shows basic plugin information, can be used to reload the plugin or to check for updates
    permission: doorlock.manage
    permission-message: §cYou are not permitted to use this command!
    usage: §c/doorlock <version|update|reload>

